@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Jan 21 12:25:35 +0330 2022
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 192a604a3bfa47889811f25f36041f47 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot CORDIC_hyperbolic_tb_behav xil_defaultlib.CORDIC_hyperbolic_tb -log elaborate.log"
call xelab  -wto 192a604a3bfa47889811f25f36041f47 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot CORDIC_hyperbolic_tb_behav xil_defaultlib.CORDIC_hyperbolic_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
